---
title: "P8130 Final Project"
author: "Xiangyi Liu (xl3048), Yueqi Zhong, Bin Yang, Pangsibo Shen"
date: "12/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(tidyverse)
library(dplyr)
library(plotly)
library(arsenal)
library(HH)
library(patchwork)


```


```{r data, include=F}
crime_df <- read.csv(file = "./HateCrimes.csv") %>% 
  mutate(hate_crimes_per_100k_splc = as.numeric(hate_crimes_per_100k_splc))
  
```


### Descriptive Statistics
```{r desp, echo=F}
my_controls <- tableby.control(
  total = T,
  test=F,  # No test p-values yet
  numeric.stats = c("meansd", "medianq1q3", "range", "Nmiss2"),
  cat.stats = c("countpct", "Nmiss2"),
  stats.labels = list(
    meansd = "Mean (SD)",
    medianq1q3 = "Median (Q1, Q3)",
    range = "Min - Max",
    Nmiss2 = "Missing",
    countpct = "N (%)"))

my_labels <- list(state = "State", unemployment = "Unemployment", urbanization = "Urbanization", median_household_income = "Median Household Income", perc_population_with_high_school_degree = "High School Education %", perc_non_citizen = "Non Citizen %", gini_index = "Gini Index", perc_non_white = " Non White %", hate_crimes_per_100k_splc = "Hate Crime Rate per 100K")

tbl<-tableby( ~ unemployment + urbanization + median_household_income + perc_population_with_high_school_degree + perc_non_citizen + gini_index + perc_non_white + hate_crimes_per_100k_splc,data = crime_df, control=my_controls,test=FALSE)
summary(tbl,title = "Descriptive Statistics: Hate Crime Rate After 2016 Election",labelTranslations = my_labels,text=TRUE)


# drop NAs
crime_df <- drop_na(crime_df)
```


### Check for outliers
```{r outlier, echo=F}
outlier_plot <- ggplot(data = crime_df, aes(hate_crimes_per_100k_splc))+
  geom_boxplot(outlier.color = "red",outlier.size = 2)+ylim(-0.5,0.5)+
  labs(title = "Outliers Detection", x = "Hate Crime Rate per 100K People")
outlier_plot

upper_bound <- quantile(crime_df$hate_crimes_per_100k_splc, 0.75)
lower_bound <- quantile(crime_df$hate_crimes_per_100k_splc, 0.25)
iqr = upper_bound-lower_bound

crime_df %>% filter(hate_crimes_per_100k_splc > upper_bound+1.5*iqr) %>% 
  dplyr::select(state, hate_crimes_per_100k_splc) %>%
  knitr::kable(digits = 2)
 

hist_before <- crime_df %>% 
  ggplot(aes(x = hate_crimes_per_100k_splc)) +
  geom_histogram(fill="#69b3a2", color="#e9ecef", alpha=0.9, aes(y = ..density..)) + 
  geom_density(color = "yellow") +
  labs(
    title = "Before Log" ,
    x = "Hate Crime per 100K Population",
    y = "Density"
  )

# qqplot - distribution of outcome
qq_before <- crime_df %>% 
  ggplot(aes(sample = hate_crimes_per_100k_splc)) + 
  stat_qq() + 
  stat_qq_line() +
  labs(
    title = "Before Log",
    x = "Theoretical",
    y = "Sample"
  )


# Take log on the outcome
crime_df <- crime_df %>% mutate(hate_crimes_per_100k_splc = log(hate_crimes_per_100k_splc))

hist_after<- crime_df %>% 
  ggplot(aes(x = hate_crimes_per_100k_splc)) +
  geom_histogram(fill="#69b3a2", color="#e9ecef", alpha=0.9, aes(y = ..density..)) + 
  geom_density(color = "yellow") +
  labs(
    title = "After Log" ,
    x = "Hate Crime per 100K Population",
    y = "Density"
  )

qq_after <- crime_df %>% 
  ggplot(aes(sample = hate_crimes_per_100k_splc)) + 
  stat_qq() + 
  stat_qq_line() +
  labs(
    title = "After Log",
    x = "Theoretical",
    y = "Sample"
  )

hist_before+qq_before
hist_after+qq_after


# crime_df <- crime_df %>% filter(hate_crimes_per_100k_splc <= upper_bound+1.5*iqr)

```


### Verify the association between hate crime rate and income inequality

```{r cor matrix}
crime_df %>% dplyr::select(-state,-unemployment,-urbanization) %>% cor() %>% knitr::kable(digits = 2)

crime_df %>% dplyr::select(-state,-unemployment,-urbanization) %>% cor() %>% corrplot::corrplot(method = "circle", type = "upper", diag=FALSE)

# Non citizen and non white are highly correlated (0.75). Only select non_citizen for model.

```

```{r}

reg_crimes = 
  lm(hate_crimes_per_100k_splc ~ factor(unemployment) + factor(urbanization) + perc_population_with_high_school_degree + median_household_income +  perc_non_citizen + gini_index, data = crime_df)

summary(reg_crimes)


vif(reg_crimes)
```


### Partial F test
```{r partial f test}

# H0: small model is better
reduced_model = lm(hate_crimes_per_100k_splc ~ factor(unemployment) + factor(urbanization) + perc_population_with_high_school_degree + median_household_income +  perc_non_citizen, data = crime_df)

summary(reduced_model)

anova(reduced_model, reg_crimes)
# reject H0, verified
```


### MLR

```{r interaction}
income_urban <- qplot(x = median_household_income, y = hate_crimes_per_100k_splc, data = crime_df, color =factor(urbanization)) + geom_smooth(method = "lm", se = FALSE) + 
  labs(x = "Median Household Income", y = "Hate Crime Rate per 100K Population") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

income_unemploy <- qplot(x = median_household_income, y = hate_crimes_per_100k_splc, data = crime_df, color =factor(unemployment)) + geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Median Household Income", y = "Hate Crime Rate per 100K Population") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))


highschool_urban <- qplot(x = perc_population_with_high_school_degree, y = hate_crimes_per_100k_splc, data = crime_df, color =factor(urbanization)) + geom_smooth(method = "lm", se = FALSE) + 
  labs(x = "Percentage Of Population With High School Degree", y = "Hate Crime Rate per 100K Population") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

highschool_unemploy <- qplot(x = perc_population_with_high_school_degree, y = hate_crimes_per_100k_splc, data = crime_df, color =factor(unemployment)) + geom_smooth(method = "lm", se = FALSE) + 
  labs(x = "Percentage Of Population With High School Degree", y = "Hate Crime Rate per 100K Population") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))


noncitizen_urban <- qplot(x = perc_non_citizen, y = hate_crimes_per_100k_splc, data = crime_df, color =factor(urbanization)) + geom_smooth(method = "lm", se = FALSE) + 
  labs(x = "Percentage Of Non-citizen", y = "Hate Crime Rate per 100K Population") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))


noncitizen_unemploy <- qplot(x = perc_non_citizen, y = hate_crimes_per_100k_splc, data = crime_df, color =factor(unemployment)) + geom_smooth(method = "lm", se = FALSE) + 
  labs(x = "Percentage Of Non-citizen", y = "Hate Crime Rate per 100K Population") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))


gini_urban <- qplot(x = gini_index, y = hate_crimes_per_100k_splc, data = crime_df, color =factor(urbanization)) + geom_smooth(method = "lm", se = FALSE) + 
  labs(x = "Gini Index", y = "Hate Crime Rate per 100K Population") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

gini_unemploy <- qplot(x = gini_index, y = hate_crimes_per_100k_splc, data = crime_df, color =factor(unemployment)) + geom_smooth(method = "lm", se = FALSE) + 
  labs(x = "Gini Index", y = "Hate Crime Rate per 100K Population") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

income_urban+income_unemploy
highschool_urban+highschool_unemploy
noncitizen_urban+noncitizen_unemploy
gini_urban+gini_unemploy

```




```{r}

int_model <- lm(hate_crimes_per_100k_splc ~  median_household_income + perc_population_with_high_school_degree + perc_non_citizen + gini_index + median_household_income * urbanization + median_household_income * unemployment + perc_population_with_high_school_degree * urbanization + perc_population_with_high_school_degree * unemployment + perc_non_citizen * urbanization + gini_index * urbanization,data = crime_df)


step(int_model, direction='backward')

# New MLR
new_reg = lm(hate_crimes_per_100k_splc ~ perc_population_with_high_school_degree + gini_index + median_household_income + urbanization * median_household_income, data = crime_df)

summary(new_reg)
```


## Dignositics
```{r}
plot(new_reg)

```







